// react/src/components/RunGraphSettings.tsx
import {
  DEFAULT_HORIZONTAL_SCALE_MULTIPLIER,
  HorizontalMode,
  VerticalMode,
  isHorizontalMode,
  isVerticalMode,
  layout,
  resetHorizontalScaleMultiplier,
  setDisabledArtifacts,
  setDisabledEdges,
  setDisabledEvents,
  setHorizontalMode,
  setHorizontalScaleMultiplier,
  setVerticalMode,
} from '@prefecthq/graphs'
import { useEffect, useState } from 'react'

type LayoutOption = `${HorizontalMode}_${VerticalMode}`

interface Option<T extends string> {
  value: T
  label: string
}

function isLayoutOption(value: string): value is LayoutOption {
  const [horizontal, vertical] = value.split('_')
  return isHorizontalMode(horizontal) && isVerticalMode(vertical)
}

const layoutOptions: Option<LayoutOption>[] = [
  {
    label: 'Temporal dependency',
    value: 'temporal_nearest-parent',
  },
  {
    label: 'Temporal sequence',
    value: 'temporal_waterfall',
  },
  {
    label: 'Dependency grid',
    value: 'dependency_nearest-parent',
  },
  {
    label: 'Sequential grid',
    value: 'dependency_waterfall',
  },
  {
    label: 'Comparative duration',
    value: 'left-aligned_duration-sorted',
  },
]

export function RunGraphSettings(): JSX.Element {
  const [selectedLayoutOption, setSelectedLayoutOption] = useState<LayoutOption>(
    `${layout.horizontal}_${layout.vertical}` as LayoutOption,
  )
  const [hideEdges, setHideEdges] = useState(layout.disableEdges)
  const [hideArtifacts, setHideArtifacts] = useState(layout.disableArtifacts)
  const [hideEvents, setHideEvents] = useState(layout.disableEvents)

  const handleLayoutChange = (value: string) => {
    if (!isLayoutOption(value)) {
      return
    }

    setSelectedLayoutOption(value)
    const [horizontal, vertical] = value.split('_') as [HorizontalMode, VerticalMode]
    setHorizontalMode(horizontal)
    setVerticalMode(vertical)
  }

  const handleHideEdges = (event: React.ChangeEvent<HTMLInputElement>) => {
    const value = event.target.checked
    setHideEdges(value)
    setDisabledEdges(value)
  }

  const handleHideArtifacts = (event: React.ChangeEvent<HTMLInputElement>) => {
    const value = event.target.checked
    setHideArtifacts(value)
    setDisabledArtifacts(value)
  }

  const handleHideEvents = (event: React.ChangeEvent<HTMLInputElement>) => {
    const value = event.target.checked
    setHideEvents(value)
    setDisabledEvents(value)
  }

  const increaseScale = () => {
    const multiplier = DEFAULT_HORIZONTAL_SCALE_MULTIPLIER + 1
    const scale = layout.horizontalScaleMultiplier * multiplier
    setHorizontalScaleMultiplier(scale)
  }

  const decreaseScale = () => {
    const multiplier = Math.abs(DEFAULT_HORIZONTAL_SCALE_MULTIPLIER - 1)
    const scale = layout.horizontalScaleMultiplier * multiplier
    setHorizontalScaleMultiplier(scale)
  }

  const resetScale = () => {
    resetHorizontalScaleMultiplier()
  }

  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      if (
        event.target instanceof HTMLInputElement ||
        event.metaKey ||
        event.ctrlKey
      ) {
        return
      }

      switch (event.key) {
        case '-':
          decreaseScale()
          break
        case '=':
          increaseScale()
          break
      }
    }

    window.addEventListener('keydown', handleKeyDown)
    return () => window.removeEventListener('keydown', handleKeyDown)
  }, [])

  return (
    <div className="run-graph-settings">
      <div>
        <h3>Layout</h3>
        {layoutOptions.map((option) => (
          <div key={option.value}>
            <input
              type="radio"
              id={option.value}
              name="layout"
              value={option.value}
              checked={selectedLayoutOption === option.value}
              onChange={(e) => handleLayoutChange(e.target.value)}
            />
            <label htmlFor={option.value}>{option.label}</label>
          </div>
        ))}
      </div>

      {(layout.isTemporal() || layout.isLeftAligned()) && (
        <div>
          <h3>Scaling</h3>
          <button onClick={decreaseScale} title="Decrease scale (-)">-</button>
          <button onClick={increaseScale} title="Increase scale (+)">+</button>
          <button onClick={resetScale}>Reset</button>
        </div>
      )}

      <hr />
      
      <div>
        <div>
          <input
            type="checkbox"
            id="hideEdges"
            checked={hideEdges}
            onChange={handleHideEdges}
          />
          <label htmlFor="hideEdges">Hide dependency arrows</label>
        </div>

        <div>
          <input
            type="checkbox"
            id="hideArtifacts"
            checked={hideArtifacts}
            onChange={handleHideArtifacts}
          />
          <label htmlFor="hideArtifacts">Hide artifacts</label>
        </div>

        <div>
          <input
            type="checkbox"
            id="hideEvents"
            checked={hideEvents}
            onChange={handleHideEvents}
          />
          <label htmlFor="hideEvents">Hide events</label>
        </div>
      </div>
    </div>
  )
}

// vue/src/components/RunGraphSettings.vue
<template>
  <p-pop-over
    class="run-graph-settings"
    auto-close
    :placement="placement"
  >
    <template #target="{ toggle }">
      <p-button
        aria-label="Run Graph Options"
        icon="CogIcon"
        flat
        @click="toggle"
      />
    </template>

    <p-overflow-menu class="run-graph-settings__menu">
      <p-label label="Layout">
        <p-radio-group :model-value="selectedLayoutOption" :options="layoutOptions" @update:model-value="setSelectedLayoutOption">
          <template #label="{ option }">
            {{ option.label }}
          </template>
        </p-radio-group>
      </p-label>
      <template v-if="layout.isTemporal() || layout.isLeftAligned()">
        <p-divider />
        <p-label label="Scaling">
          <div class="flex items-center gap-2">
            <p-button title="Decrease scale (-)" small icon="MinusIcon" @click="decreaseScale" />
            <p-button title="Increase scale (+)" small icon="PlusIcon" @click="increaseScale" />
            <p-button small @click="resetScale">
              Reset
            </p-button>
          </div>
        </p-label>
      </template>
      <p-divider />
      <p-checkbox :model-value="hideEdges" label="Hide dependency arrows" @update:model-value="setHideEdges" />
      <p-checkbox :model-value="hideArtifacts" label="Hide artifacts" @update:model-value="setHideArtifacts" />
      <p-checkbox :model-value="hideEvents" label="Hide events" @update:model-value="setHideEvents" />
    </p-overflow-menu>
  </p-pop-over>
</template>

<script lang="ts" setup>
  import { CheckboxModel, PButton, positions, PPopOver, SelectModelValue } from '@prefecthq/prefect-design'
  import { useKeyDown } from '@prefecthq/vue-compositions'
  import { ref } from 'vue'
  import {
    DEFAULT_HORIZONTAL_SCALE_MULTIPLIER,
    HorizontalMode,
    isHorizontalMode,
    isVerticalMode,
    VerticalMode,
    layout,
    resetHorizontalScaleMultiplier,
    setDisabledArtifacts,
    setDisabledEdges,
    setDisabledEvents,
    setHorizontalMode,
    setHorizontalScaleMultiplier,
    setVerticalMode,
  } from '@prefecthq/graphs'
  import { eventTargetIsInput } from '@/utilities/keyboard'

  type Option<T extends string> = {
    value: T,
    label: string,
  }

  const placement = [positions.topRight, positions.bottomRight, positions.topLeft, positions.bottomLeft]

  type LayoutOption = `${HorizontalMode}_${VerticalMode}`

  function isLayoutOption(value: string): value is LayoutOption {
    const [horizontal, vertical] = value.split('_')

    return isHorizontalMode(horizontal) && isVerticalMode(vertical)
  }

  const layoutOptions: Option<LayoutOption>[] = [
    {
      label: 'Temporal dependency',
      value: 'temporal_nearest-parent',
    }, {
      label: 'Temporal sequence',
      value: 'temporal_waterfall',
    }, {
      label: 'Dependency grid',
      value: 'dependency_nearest-parent',
    }, {
      label: 'Sequential grid',
      value: 'dependency_waterfall',
    }, {
      label: 'Comparative duration',
      value: 'left-aligned_duration-sorted',
    },
  ]

  const selectedLayoutOption = ref<LayoutOption>(`${layout.horizontal}_${layout.vertical}`)

  function setSelectedLayoutOption(value: SelectModelValue): void {
    if (typeof value !== 'string' || !isLayoutOption(value)) {
      return
    }

    selectedLayoutOption.value = value

    const [horizontal, vertical] = value.split('_') as [HorizontalMode, VerticalMode]

    setHorizontalMode(horizontal)
    setVerticalMode(vertical)
  }

  const hideEdges = ref(layout.disableEdges)

  function setHideEdges(value: CheckboxModel): void {
    hideEdges.value = Boolean(value)
    setDisabledEdges(hideEdges.value)
  }

  const hideArtifacts = ref(layout.disableArtifacts)

  function setHideArtifacts(value: CheckboxModel): void {
    hideArtifacts.value = Boolean(value)
    setDisabledArtifacts(hideArtifacts.value)
  }

  const hideEvents = ref(layout.disableEvents)

  function setHideEvents(value: CheckboxModel): void {
    hideEvents.value = Boolean(value)
    setDisabledEvents(hideEvents.value)
  }

  function increaseScale(): void {
    const multiplier = DEFAULT_HORIZONTAL_SCALE_MULTIPLIER + 1
    const scale = layout.horizontalScaleMultiplier * multiplier

    setHorizontalScaleMultiplier(scale)
  }

  function decreaseScale(): void {
    const multiplier = Math.abs(DEFAULT_HORIZONTAL_SCALE_MULTIPLIER - 1)
    const scale = layout.horizontalScaleMultiplier * multiplier

    setHorizontalScaleMultiplier(scale)
  }

  useKeyDown(['-', '='], shortcutHandler)

  function shortcutHandler(event: KeyboardEvent): void {
    if (eventTargetIsInput(event.target) || event.metaKey || event.ctrlKey) {
      return
    }

    switch (event.key) {
      case '-':
        decreaseScale()
        break
      case '=':
        increaseScale()
        break
    }
  }

  function resetScale(): void {
    resetHorizontalScaleMultiplier()
  }
</script>

<style>
.run-graph-settings {
  display: inline-block;
}

.run-graph-settings__menu {
  padding: 0.5rem;
}
</style>
