// src/components/RunGraph.vue
<template>
  <div class="run-graph" :class="classes.root">
    <div ref="stage" class="run-graph__stage" />
    <div class="run-graph__actions">
      <p-button title="Recenter graph (c)" icon="Target" flat @click="center" />
      <p-button title="Toggle fullscreen (f)" icon="ArrowsPointingOutIcon" flat @click="toggleFullscreen" />
      <RunGraphSettings />
    </div>
  </div>
</template>

<script lang="ts" setup>
  import { useKeyDown } from '@prefecthq/vue-compositions'
  import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
  import RunGraphSettings from '@/components/RunGraphSettings.vue'
  import { RunGraphProps } from '@/models/RunGraph'
  import { GraphItemSelection } from '@/models/selection'
  import { ViewportDateRange } from '@/models/viewport'
  import { start, stop, centerViewport, updateViewportFromDateRange } from '@/objects'
  import { emitter } from '@/objects/events'
  import { selectItem } from '@/objects/selection'
  import { eventTargetIsInput } from '@/utilities/keyboard'

  // using the props object as a whole
  // eslint-disable-next-line vue/no-unused-properties
  const props = withDefaults(defineProps<RunGraphProps>(), {
    fullscreen: null,
    selected: null,
  })

  const emit = defineEmits<{
    (event: 'update:viewport', value: ViewportDateRange): void,
    (event: 'update:fullscreen', value: boolean): void,
    (event: 'update:selected', value: GraphItemSelection | null): void,
  }>()

  const stage = ref<HTMLDivElement>()

  const fullscreenInternal = ref(false)
  const fullscreenModel = computed({
    get() {
      return props.fullscreen ?? fullscreenInternal.value
    },
    set(value) {
      fullscreenInternal.value = value
      emit('update:fullscreen', value)
    },
  })

  watch(() => props.selected, selected => selectItem(selected))

  emitter.on('itemSelected', nodeId => emit('update:selected', nodeId))

  watch(() => props.viewport, viewport => updateViewportFromDateRange(viewport))

  const classes = computed(() => ({
    root: {
      'run-graph--fullscreen': fullscreenModel.value,
    },
  }))

  emitter.on('viewportDateRangeUpdated', range => emit('update:viewport', range))

  function center(): void {
    centerViewport({ animate: true })
  }

  function toggleFullscreen(): void {
    fullscreenModel.value = !fullscreenModel.value
  }

  onMounted(() => {
    if (!stage.value) {
      throw new Error('Stage does not exist')
    }

    start({
      stage: stage.value,
      props,
    })
  })

  onBeforeUnmount(() => {
    stop()
  })

  useKeyDown(['c', 'f', 'Escape'], shortcutHandler)

  function shortcutHandler(event: KeyboardEvent): void {
    if (eventTargetIsInput(event.target) || event.metaKey || event.ctrlKey) {
      return
    }

    switch (event.key) {
      case 'c':
        center()
        break
      case 'f':
        toggleFullscreen()
        break
      case 'Escape':
        if (fullscreenModel.value) {
          toggleFullscreen()
        }
        break
    }
  }
</script>

<style>
.run-graph {
  position: relative;
}

.run-graph--fullscreen {
  position: fixed;
  height: 100vh !important;
  width: 100vw !important;
  left: 0;
  top: 0;
}

.run-graph__stage,
.run-graph__stage > canvas {
  width: 100%;
  height: 100%;
}

.run-graph__actions {
  position: absolute;
  bottom: 0;
  right: 0;
  padding: theme('spacing.2');
}
</style>

// react/src/components/RunGraph.tsx
import { CSSProperties, useEffect, useRef, useState } from 'react'
import {
  GraphItemSelection,
  RunGraphConfig,
  ViewportDateRange,
  centerViewport,
  emitter,
  selectItem,
  setConfig,
  start,
  stop,
  updateViewportFromDateRange,
} from '@prefecthq/graphs'
import { RunGraphSettings } from './RunGraphSettings'

type RunGraphProps = {
  viewport?: ViewportDateRange
  onViewportChange?: (viewport: ViewportDateRange) => void
  selected?: GraphItemSelection
  onSelectedChange?: (selected: GraphItemSelection | null) => void
  config: RunGraphConfig
  className?: string
  style?: CSSProperties
  fullscreen?: boolean
  onFullscreenChange?: (fullscreen: boolean) => void
}

export function RunGraph({
  viewport,
  onViewportChange,
  selected,
  onSelectedChange,
  config,
  className,
  style,
  fullscreen: controlledFullscreen,
  onFullscreenChange,
}: RunGraphProps) {
  const stageRef = useRef<HTMLDivElement>(null)
  const [internalFullscreen, setInternalFullscreen] = useState(false)

  const fullscreen = controlledFullscreen ?? internalFullscreen

  const updateFullscreen = (value: boolean) => {
    setInternalFullscreen(value)
    onFullscreenChange?.(value)
  }

  useEffect(() => {
    setConfig(config)
  }, [config])

  useEffect(() => {
    if (!stageRef.current) {
      throw new Error('Stage does not exist')
    }

    start({
      stage: stageRef.current,
      config,
    })

    return () => {
      stop()
    }
  }, [config])

  useEffect(() => {
    if (selected !== undefined) {
      selectItem(selected)
    }
  }, [selected])

  useEffect(() => {
    if (viewport) {
      updateViewportFromDateRange(viewport)
    }
  }, [viewport])

  useEffect(() => {
    const handleItemSelected = (nodeId: GraphItemSelection) => {
      onSelectedChange?.(nodeId)
    }

    const handleViewportUpdate = (range: ViewportDateRange) => {
      onViewportChange?.(range)
    }

    emitter.on('itemSelected', handleItemSelected)
    emitter.on('viewportDateRangeUpdated', handleViewportUpdate)

    return () => {
      emitter.off('itemSelected', handleItemSelected)
      emitter.off('viewportDateRangeUpdated', handleViewportUpdate)
    }
  }, [onSelectedChange, onViewportChange])

  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      if (
        isEventTargetInput(event.target) ||
        event.metaKey ||
        event.ctrlKey
      ) {
        return
      }

      switch (event.key) {
        case 'c':
          center()
          break
        case 'f':
          toggleFullscreen()
          break
        case 'Escape':
          if (fullscreen) {
            toggleFullscreen()
          }
          break
      }
    }

    document.addEventListener('keydown', handleKeyDown)
    return () => document.removeEventListener('keydown', handleKeyDown)
  }, [fullscreen])

  const center = () => {
    centerViewport({ animate: true })
  }

  const toggleFullscreen = () => {
    updateFullscreen(!fullscreen)
  }

  const isEventTargetInput = (target: EventTarget | null): boolean => {
    if (!target || !(target instanceof HTMLElement)) {
      return false
    }
    return ['INPUT', 'TEXTAREA', 'SELECT'].includes(target.tagName)
  }

  return (
    <div 
      className={`run-graph ${fullscreen ? 'run-graph--fullscreen' : ''} ${className ?? ''}`}
      style={style}
    >
      <div ref={stageRef} className="run-graph__stage" />
      <div className="run-graph__actions">
        <button 
          title="Recenter graph (c)" 
          onClick={center}
          className="p-button p-button--flat"
        >
          Recenter
        </button>
        <button 
          title="Toggle fullscreen (f)" 
          onClick={toggleFullscreen}
          className="p-button p-button--flat"
        >
          Fullscreen
        </button>
        <RunGraphSettings />
      </div>

      <style>{`
        .run-graph {
          position: relative;
        }

        .run-graph--fullscreen {
          position: fixed;
          height: 100vh !important;
          width: 100vw !important;
          left: 0;
          top: 0;
        }

        .run-graph__stage,
        .run-graph__stage > canvas {
          width: 100%;
          height: 100%;
        }

        .run-graph__actions {
          position: absolute;
          bottom: 0.5rem;
          right: 0.5rem;
        }
      `}</style>
    </div>
  )
}
